apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: book-verse-plus
build:
  googleCloudBuild:
    projectId: book-verse-plus
  # local:
  #   push: false
  artifacts:
    - image: gcr.io/book-verse-plus/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "**/*.js"
manifests:
  rawYaml:
    - infra/k8s/services/*
    - infra/k8s/deployments/*
    - infra/k8s/ingress/*
