apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-verse-plus-books-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-verse-plus-books
  template:
    metadata:
      labels:
        app: book-verse-plus-books
    spec:
      containers:
        - name: books
          image: gcr.io/book-verse-plus/books
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
