apiVersion: v1
kind: Service
metadata:
  name: book-verse-plus-auth-mongo-srv
spec:
  selector:
    app: book-verse-plus-auth-mongo
  ports:
    - name: db
      port: 27017
      targetPort: 27017
      protocol: TCP
