apiVersion: v1
kind: Service
metadata:
  name: book-verse-plus-books-postgres-srv
spec:
  selector:
    app: book-verse-plus-books-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
