apiVersion: v1
kind: Service
metadata:
  name: book-verse-plus-books-srv
spec:
  type: ClusterIP
  selector:
    app: book-verse-plus-books
  ports:
    - name: book-verse-plus-books
      protocol: TCP
      port: 3000
      targetPort: 3000
